server:
  port: 8092
  error:
    include-message: always

spring:
  application:
    name: customer-service
  cloud:
    config:
      uri: http://localhost:8081
      username: root
      password: s3cr3t
  boot:
    admin:
      client:
        url: http://localhost:8088

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_EVENT_PATTERN:-5%p} %m%n"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
